version: "3"
services:
  eattogether-sms:
    container_name: "eattogether-sms"
    image: "node:10"
    volumes:
      - ./:/data0/server/sms
    environment:
      - TZ=Asia/Shanghai
      - APP_ENV=development
    command: 
      - /bin/sh
      - -c
      - |
        npm install --prefix /data0/server/sms
        npm start --prefix /data0/server/sms
